Draft of mingw port. At least, it compiles now.
Signed-off-by: ofry <tim4job@bmail.ru>

diff --git a/boot-strap b/boot-strap
--- a/boot-strap
+++ b/boot-strap
@@ -134,14 +134,14 @@ case "$Mydir" in
 esac
 
 Usage() {
-	[ "$1" ] && echo "ERROR: $@" >&2
+	[ "$1" ] && echo "__ERROR: $@" >&2
 	echo "Usage:" >&2
 	echo "$0 [--<configure_arg> ...][<prefix>][--install]" >&2
 	exit 1
 }
 
 Error() {
-	echo "ERROR: $@" >&2
+	echo "__ERROR: $@" >&2
 	exit 1
 }
 
diff --git a/mk/install-mk b/mk/install-mk
--- a/mk/install-mk
+++ b/mk/install-mk
@@ -113,7 +113,7 @@ Do() {
 }
 
 Error() {
-	echo "ERROR: $@" >&2
+	echo "__ERROR: $@" >&2
 	exit 1
 }
 
